### ISSUE TITLE
格式不够专业(逼格)

### ISSUE THREAD

**Issue by Revolution1** [keepeat/eatoverworld#10]
建议内容（全部 5 分制并配图和简评）：

店面：

- 装修
- 卫生
- 服务

菜品：

- 口味
- 外形
- 健康
- 速度

推荐菜：xxxx
不推荐菜：xxxx

**Comment by yowenter** [comment]
HI, 
Since we use google spreadsheet app to maintain restaurants. 
I'm closing this issue. :-)


https://docs.google.com/spreadsheets/d/1sP0aUnPW6W9ODIuUUSl6ISnkpQAI0ekxvF1C6yFxotE/edit?usp=sharing
