### ISSUE TITLE
应该只提供名字，点评可以自动抓取

### ISSUE THREAD

**Issue by jjyr** [keepeat/eatoverworld#3]
现在录入太麻烦了，懒得录入...

**Comment by yowenter** [comment]
@lyn716

**Comment by yowenter** [comment]
HI, 
Since we use google spreadsheet app to maintain restaurants. 
I'm closing this issue. :-)


https://docs.google.com/spreadsheets/d/1sP0aUnPW6W9ODIuUUSl6ISnkpQAI0ekxvF1C6yFxotE/edit?usp=sharing
